version: '3'

services:

  client:
    build:
      context: client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    networks:
      - agent-domain
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 3010:3010

    env_file:
      - agent/.env
    networks:
      - agent-domain
    entrypoint: /bin/bash
    command: [
      "-c",
      "python -u app/main.py;"
    ]
  agent-admin:
    build:
      context: agent-admin
      dockerfile: Dockerfile
    depends_on:
      - agent
    env_file:
      - agent/.env
    networks:
      - agent-domain
    volumes:
      - ./agent-admin/notebooks:/workspace
    ports:
      - "8888:8888"
  agent-wallet-db:
    image: postgres:11
    container_name: agent-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - agent/.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agent-domain
    tty: true
  agent:
    build:
      context: agent
      dockerfile: Dockerfile.prod
    env_file:
      - agent/.env
    ports:
      - 3020:3020
      - 3021:3021
    networks:
      - agent-domain
networks:
  agent-domain: