version: "3"
services:
  client:
    tty: true
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - agent-domain
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 3010:3010

    env_file:
      - agent/.env
    networks:
      - agent-domain
    entrypoint: /bin/bash
    command: [
      "-c",
      "python -u app/main.py;"
    ]
  agent-admin:
    build:
      context: agent-admin
      dockerfile: Dockerfile
    depends_on:
      - agent
    networks:
      - agent-domain
    env_file:
      - agent/.env
    volumes:
      - ./agent-admin/notebooks:/workspace
    ports:
      - "8888:8888"
  agent-wallet-db:
    image: postgres:11
    container_name: agent-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - agent/.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agent-domain
    tty: true
  ngrok-agent:
    image: wernight/ngrok
    command: ngrok http agent:3020 --log stdout
    networks:
      - agent-domain
  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    env_file:
      - agent/.env
    ports:
      - 3020:3020
      - 3021:3021
    depends_on:
      - agent-wallet-db
    networks:
      - agent-domain
networks:
  agent-domain: